### ISSUE TITLE
"Error Opening URL, it may not be a valid URI" on all shares

### ISSUE THREAD

**Issue by theofficialgman** [Martichou/rquickshare#165]
On latest release https://github.com/Martichou/rquickshare/releases/tag/v0.11.0 I get the error in the title on trying to use the "Open" button in the application. Other versions untested so I do not know if it previously worked.

Tested with PDF and TXT files that both have default applications assigned in the system via mime type. Installed the .deb version of the application. No logs output via terminal when clicking the open button.

```
           `.:/ossyyyysso/:.                garrett@garrett-desktop
        .:oyyyyyyyyyyyyyyyyyyo:`            -----------------------
      -oyyyyyyyodMMyyyyyyyysyyyyo-          OS: Kubuntu noble 24.04 x86_64
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-        Host: MS-7B48 (1.0)
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo      Kernel: Linux 6.8.0-40-generic
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`     Uptime: 8 hours, 10 mins
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo     Packages: 5420 (dpkg), 13 (flatpak), 1 (snap)
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-    Shell: bash 5.2.21
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo    Display (LG HDR 4K): 3840x2160 @ 60 Hz (as 2560x1440) in 27″ [External]
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy    DE: KDE Plasma 6.1.3
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy    WM: KWin (Wayland)
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo    WM Theme: Breeze
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-    Theme: Breeze (Dark) [Qt], Breeze-Dark [GTK2], Breeze [GTK3/4]
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo     Icons: breeze-dark [Qt], breeze-dark [GTK2/3/4]
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo      Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo       Cursor: breeze (24px)
    -syyyyyyyyydMMMysyyydMMMysyyyys-        Terminal: konsole 24.5.2
      -oyyyyyyydMMyyyyyyysosyyyyo-          CPU: Intel(R) Core(TM) i5-8600K (6) @ 4.80 GHz
        ./oyyyyyyyyyyyyyyyyyyo/.            GPU 1: Intel UHD Graphics 630 @ 1.15 GHz [Integrated]
           `.:/oosyyyysso/:.`               GPU 2: AMD Radeon RX 570 Series [Discrete]
                                            Memory: 5.00 GiB / 15.52 GiB (32%)
                                            Swap: 3.50 MiB / 7.76 GiB (0%)
                                            Disk (/): 334.50 GiB / 496.11 GiB (67%) - ext4
                                            Disk (/media/garrett/HDD): 178.94 GiB / 631.48 GiB (28%) - exfat
                                            Disk (/media/garrett/HDD-Linux): 158.52 GiB / 915.82 GiB (17%) - ext4
                                            Disk (/media/garrett/HDD-Win): 79.94 GiB / 300.00 GiB (27%) - fuseblk [Read-only]
                                            Local IP (enp3s0): 10.0.0.80/24
                                            Locale: en_US.UTF-8

                                                                    
                                                                    
```

**Comment by Martichou** [comment]
Can you launch it with TRACE level logs as explained here and report back with them?

https://github.com/Martichou/rquickshare/pull/104

**Comment by Martichou** [comment]
Fixed: https://github.com/Martichou/rquickshare/releases/tag/v0.11.1

**Comment by theofficialgman** [comment]
Not properly fixed.

This just opens the file explorer to the folder that the file was downloaded to.
I expect that clicking 'Open' actually opens the application with the default MIME type application (eg: `xdg-open /path/to/file`)

**Comment by Martichou** [comment]
Indeed, but that was not the case neither before :) 
So I'm considering this issue as done, and will add your proposition to directly open files in their defined viewer. But I have to say that I'm not sure I'll spend time doing it as it would help ofc, but will introduce complexity as it would mean we'd need to handle different case if we send one file or multiple files. Anyway, adding it in the backlog 👍 (here https://github.com/users/Martichou/projects/1)

**Comment by ironhak** [comment]
Hello, this is still a problem. To me it happens when I share a text snippet that contains some test and a URL.
